# Generated by Django 5.2.8 on 2025-12-22 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to='tv/backdrop/'),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='tv/posters/'),
        ),
    ]
