# Generated by Django 5.2.8 on 2025-12-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_tvshow_backdrop_tvshow_episodes_tvshow_seasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(upload_to='movies/backdrop/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movies/posters/'),
        ),
    ]
